DIM X AS INTEGER
DIM WRD AS STRING
DIM REVWRD AS STRING
DIM B AS STRING
CLS
DO
    INPUT "ENTER FIRST WORD", WRD
    PRINT
    PRINT
    PRINT
    FOR X = LEN(WRD) TO 1 STEP -1
        REVWRD = REVWRD + MID$(WRD, X, 1)
    NEXT X
    PRINT
    PRINT
    PRINT "ORIGINAL WORD", UCASE$(WRD)
    PRINT "REVERSE WORD", UCASE$(REVWRD)
    IF WRD = REVWRD THEN
        PRINT "THE WORD "; WRD; "IS A PALINDROME"
    ELSE
        PRINT "THE WORD "; WRD; "IS NOT A PALINDROME"
    END IF
    PRINT
    PRINT
    PRINT
    DO
        INPUT "WOULD YOU LIKE TO TRY AGAIN(Y/N)", B
        B = UCASE$(B)
    LOOP UNTIL B = "Y" OR B = "N"
LOOP UNTIL B = "N"


